version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "video-scanner"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4lofd4ytdkcc"
s3_prefix = "video-scanner"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

